"""MMSI -> flag state, via the ITU-R M.585 MID (pure, no I/O).

AIS carries no flag field: AISStream's ShipStaticData has Name, CallSign, Type,
IMO, Destination, Dimension, ETA and Draught, and none of them is a country. The
country is instead encoded in the MMSI itself -- the first three digits of a
nine-digit MMSI are the Maritime Identification Digits assigned to the
registering administration.

Derived on read rather than stored: the flag is a pure function of `mmsi`, which
`ais_positions` already holds, so a column would only duplicate it -- and would
need a hand-run ALTER TABLE (there is no Alembic here) plus a backfill, and
would go stale if an entry below is ever corrected.

MID_COUNTRIES is generated, not hand-written: built from the ITU table published
on Wikipedia cross-checked entry-for-entry against an independent MID dataset.
Both sources carried the same 292 MIDs with no set difference.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Flag:
    """A registering administration: ISO 3166-1 alpha-2 code and display name."""

    iso2: str
    country: str


# MID -> flag. Keys are the three digits as a string, so the lookup is a plain
# slice of str(mmsi) with no arithmetic. Assigned MIDs run 201-775.
MID_COUNTRIES: dict[str, Flag] = {
    "201": Flag("AL", "Albania"),
    "202": Flag("AD", "Andorra"),
    "203": Flag("AT", "Austria"),
    "204": Flag("PT", "Azores"),
    "205": Flag("BE", "Belgium"),
    "206": Flag("BY", "Belarus"),
    "207": Flag("BG", "Bulgaria"),
    "208": Flag("VA", "Vatican City State"),
    "209": Flag("CY", "Cyprus"),
    "210": Flag("CY", "Cyprus"),
    "211": Flag("DE", "Germany"),
    "212": Flag("CY", "Cyprus"),
    "213": Flag("GE", "Georgia"),
    "214": Flag("MD", "Moldova"),
    "215": Flag("MT", "Malta"),
    "216": Flag("AM", "Armenia"),
    "218": Flag("DE", "Germany"),
    "219": Flag("DK", "Denmark"),
    "220": Flag("DK", "Denmark"),
    "224": Flag("ES", "Spain"),
    "225": Flag("ES", "Spain"),
    "226": Flag("FR", "France"),
    "227": Flag("FR", "France"),
    "228": Flag("FR", "France"),
    "229": Flag("MT", "Malta"),
    "230": Flag("FI", "Finland"),
    "231": Flag("FO", "Faroe Islands"),
    "232": Flag("GB", "United Kingdom"),
    "233": Flag("GB", "United Kingdom"),
    "234": Flag("GB", "United Kingdom"),
    "235": Flag("GB", "United Kingdom"),
    "236": Flag("GI", "Gibraltar"),
    "237": Flag("GR", "Greece"),
    "238": Flag("HR", "Croatia"),
    "239": Flag("GR", "Greece"),
    "240": Flag("GR", "Greece"),
    "241": Flag("GR", "Greece"),
    "242": Flag("MA", "Morocco"),
    "243": Flag("HU", "Hungary"),
    "244": Flag("NL", "Netherlands"),
    "245": Flag("NL", "Netherlands"),
    "246": Flag("NL", "Netherlands"),
    "247": Flag("IT", "Italy"),
    "248": Flag("MT", "Malta"),
    "249": Flag("MT", "Malta"),
    "250": Flag("IE", "Republic of Ireland"),
    "251": Flag("IS", "Iceland"),
    "252": Flag("LI", "Liechtenstein"),
    "253": Flag("LU", "Luxembourg"),
    "254": Flag("MC", "Monaco"),
    "255": Flag("PT", "Madeira"),
    "256": Flag("MT", "Malta"),
    "257": Flag("NO", "Norway"),
    "258": Flag("NO", "Norway"),
    "259": Flag("NO", "Norway"),
    "261": Flag("PL", "Poland"),
    "262": Flag("ME", "Montenegro"),
    "263": Flag("PT", "Portugal"),
    "264": Flag("RO", "Romania"),
    "265": Flag("SE", "Sweden"),
    "266": Flag("SE", "Sweden"),
    "267": Flag("SK", "Slovakia"),
    "268": Flag("SM", "San Marino"),
    "269": Flag("CH", "Switzerland"),
    "270": Flag("CZ", "Czech Republic"),
    "271": Flag("TR", "Turkey"),
    "272": Flag("UA", "Ukraine"),
    "273": Flag("RU", "Russian Federation"),
    "274": Flag("MK", "North Macedonia"),
    "275": Flag("LV", "Latvia"),
    "276": Flag("EE", "Estonia"),
    "277": Flag("LT", "Lithuania"),
    "278": Flag("SI", "Slovenia"),
    "279": Flag("RS", "Serbia"),
    "301": Flag("AI", "Anguilla"),
    "303": Flag("US", "Alaska"),
    "304": Flag("AG", "Antigua and Barbuda"),
    "305": Flag("AG", "Antigua and Barbuda"),
    "306": Flag("CW", "Former Netherlands Antilles"),
    "307": Flag("AW", "Aruba"),
    "308": Flag("BS", "Bahamas"),
    "309": Flag("BS", "Bahamas"),
    "310": Flag("BM", "Bermuda"),
    "311": Flag("BS", "Bahamas"),
    "312": Flag("BZ", "Belize"),
    "314": Flag("BB", "Barbados"),
    "316": Flag("CA", "Canada"),
    "319": Flag("KY", "Cayman Islands"),
    "321": Flag("CR", "Costa Rica"),
    "323": Flag("CU", "Cuba"),
    "325": Flag("DM", "Dominica"),
    "327": Flag("DO", "Dominican Republic"),
    "329": Flag("GP", "Guadeloupe"),
    "330": Flag("GD", "Grenada"),
    "331": Flag("GL", "Greenland"),
    "332": Flag("GT", "Guatemala"),
    "334": Flag("HN", "Honduras"),
    "336": Flag("HT", "Haiti"),
    "338": Flag("US", "United States of America"),
    "339": Flag("JM", "Jamaica"),
    "341": Flag("KN", "Saint Kitts and Nevis"),
    "343": Flag("LC", "Saint Lucia"),
    "345": Flag("MX", "Mexico"),
    "347": Flag("MQ", "Martinique"),
    "348": Flag("MS", "Montserrat"),
    "350": Flag("NI", "Nicaragua"),
    "351": Flag("PA", "Panama"),
    "352": Flag("PA", "Panama"),
    "353": Flag("PA", "Panama"),
    "354": Flag("PA", "Panama"),
    "355": Flag("PA", "Panama"),
    "356": Flag("PA", "Panama"),
    "357": Flag("PA", "Panama"),
    "358": Flag("PR", "Puerto Rico"),
    "359": Flag("SV", "El Salvador"),
    "361": Flag("PM", "Saint Pierre and Miquelon"),
    "362": Flag("TT", "Trinidad and Tobago"),
    "364": Flag("TC", "Turks and Caicos Islands"),
    "366": Flag("US", "United States of America"),
    "367": Flag("US", "United States of America"),
    "368": Flag("US", "United States of America"),
    "369": Flag("US", "United States of America"),
    "370": Flag("PA", "Panama"),
    "371": Flag("PA", "Panama"),
    "372": Flag("PA", "Panama"),
    "373": Flag("PA", "Panama"),
    "374": Flag("PA", "Panama"),
    "375": Flag("VC", "Saint Vincent and the Grenadines"),
    "376": Flag("VC", "Saint Vincent and the Grenadines"),
    "377": Flag("VC", "Saint Vincent and the Grenadines"),
    "378": Flag("VG", "British Virgin Islands"),
    "379": Flag("VI", "United States Virgin Islands"),
    "401": Flag("AF", "Afghanistan"),
    "403": Flag("SA", "Saudi Arabia"),
    "405": Flag("BD", "Bangladesh"),
    "408": Flag("BH", "Bahrain"),
    "410": Flag("BT", "Bhutan"),
    "412": Flag("CN", "China"),
    "413": Flag("CN", "China"),
    "414": Flag("CN", "China"),
    "416": Flag("TW", "Taiwan"),
    "417": Flag("LK", "Sri Lanka"),
    "419": Flag("IN", "India"),
    "422": Flag("IR", "Iran"),
    "423": Flag("AZ", "Azerbaijan"),
    "425": Flag("IQ", "Iraq"),
    "428": Flag("IL", "Israel"),
    "431": Flag("JP", "Japan"),
    "432": Flag("JP", "Japan"),
    "434": Flag("TM", "Turkmenistan"),
    "436": Flag("KZ", "Kazakhstan"),
    "437": Flag("UZ", "Uzbekistan"),
    "438": Flag("JO", "Jordan"),
    "440": Flag("KR", "South Korea"),
    "441": Flag("KR", "South Korea"),
    "443": Flag("PS", "Palestinian Authority"),
    "445": Flag("KP", "North Korea"),
    "447": Flag("KW", "Kuwait"),
    "450": Flag("LB", "Lebanon"),
    "451": Flag("KG", "Kyrgyzstan"),
    "453": Flag("MO", "Macao"),
    "455": Flag("MV", "Maldives"),
    "457": Flag("MN", "Mongolia"),
    "459": Flag("NP", "Nepal"),
    "461": Flag("OM", "Oman"),
    "463": Flag("PK", "Pakistan"),
    "466": Flag("QA", "Qatar"),
    "468": Flag("SY", "Syrian Arab Republic"),
    "470": Flag("AE", "United Arab Emirates"),
    "471": Flag("AE", "United Arab Emirates"),
    "472": Flag("TJ", "Tajikistan"),
    "473": Flag("YE", "Yemen"),
    "475": Flag("YE", "Yemen"),
    "477": Flag("HK", "Hong Kong"),
    "478": Flag("BA", "Bosnia and Herzegovina"),
    "501": Flag("FR", "Adélie Land"),
    "503": Flag("AU", "Australia"),
    "506": Flag("MM", "Myanmar"),
    "508": Flag("BN", "Brunei Darussalam"),
    "510": Flag("FM", "Federated States of Micronesia"),
    "511": Flag("PW", "Palau"),
    "512": Flag("NZ", "New Zealand"),
    "514": Flag("KH", "Cambodia"),
    "515": Flag("KH", "Cambodia"),
    "516": Flag("CX", "Christmas Island"),
    "518": Flag("CK", "Cook Islands"),
    "520": Flag("FJ", "Fiji"),
    "523": Flag("CC", "Cocos (Keeling) Islands"),
    "525": Flag("ID", "Indonesia"),
    "529": Flag("KI", "Kiribati"),
    "531": Flag("LA", "Lao People's Democratic Republic"),
    "533": Flag("MY", "Malaysia"),
    "536": Flag("MP", "Northern Mariana Islands"),
    "538": Flag("MH", "Marshall Islands"),
    "540": Flag("NC", "New Caledonia"),
    "542": Flag("NU", "Niue"),
    "544": Flag("NR", "Nauru"),
    "546": Flag("PF", "French Polynesia"),
    "548": Flag("PH", "Philippines"),
    "550": Flag("TL", "Timor-Leste"),
    "553": Flag("PG", "Papua New Guinea"),
    "555": Flag("PN", "Pitcairn Islands"),
    "557": Flag("SB", "Solomon Islands"),
    "559": Flag("AS", "American Samoa"),
    "561": Flag("WS", "Samoa"),
    "563": Flag("SG", "Singapore"),
    "564": Flag("SG", "Singapore"),
    "565": Flag("SG", "Singapore"),
    "566": Flag("SG", "Singapore"),
    "567": Flag("TH", "Thailand"),
    "570": Flag("TO", "Tonga"),
    "572": Flag("TV", "Tuvalu"),
    "574": Flag("VN", "Vietnam"),
    "576": Flag("VU", "Vanuatu"),
    "577": Flag("VU", "Vanuatu"),
    "578": Flag("WF", "Wallis and Futuna"),
    "601": Flag("ZA", "South Africa"),
    "603": Flag("AO", "Angola"),
    "605": Flag("DZ", "Algeria"),
    "607": Flag("FR", "Saint Paul and Amsterdam Islands"),
    "608": Flag("GB", "Ascension Island"),
    "609": Flag("BI", "Burundi"),
    "610": Flag("BJ", "Benin"),
    "611": Flag("BW", "Botswana"),
    "612": Flag("CF", "Central African Republic"),
    "613": Flag("CM", "Cameroon"),
    "615": Flag("CG", "Republic of the Congo"),
    "616": Flag("KM", "Comoros"),
    "617": Flag("CV", "Cape Verde"),
    "618": Flag("FR", "Crozet Archipelago"),
    "619": Flag("CI", "Côte d'Ivoire"),
    "620": Flag("KM", "Comoros"),
    "621": Flag("DJ", "Djibouti"),
    "622": Flag("EG", "Egypt"),
    "624": Flag("ET", "Ethiopia"),
    "625": Flag("ER", "Eritrea"),
    "626": Flag("GA", "Gabon"),
    "627": Flag("GH", "Ghana"),
    "629": Flag("GM", "Gambia"),
    "630": Flag("GW", "Guinea-Bissau"),
    "631": Flag("GQ", "Equatorial Guinea"),
    "632": Flag("GN", "Guinea"),
    "633": Flag("BF", "Burkina Faso"),
    "634": Flag("KE", "Kenya"),
    "635": Flag("FR", "Kerguelen Islands"),
    "636": Flag("LR", "Liberia"),
    "637": Flag("LR", "Liberia"),
    "638": Flag("SS", "South Sudan"),
    "642": Flag("LY", "Libya"),
    "644": Flag("LS", "Lesotho"),
    "645": Flag("MU", "Mauritius"),
    "647": Flag("MG", "Madagascar"),
    "649": Flag("ML", "Mali"),
    "650": Flag("MZ", "Mozambique"),
    "654": Flag("MR", "Mauritania"),
    "655": Flag("MW", "Malawi"),
    "656": Flag("NE", "Niger"),
    "657": Flag("NG", "Nigeria"),
    "659": Flag("NA", "Namibia"),
    "660": Flag("RE", "Réunion"),
    "661": Flag("RW", "Rwanda"),
    "662": Flag("SD", "Sudan"),
    "663": Flag("SN", "Senegal"),
    "664": Flag("SC", "Seychelles"),
    "665": Flag("SH", "Saint Helena"),
    "666": Flag("SO", "Somalia"),
    "667": Flag("SL", "Sierra Leone"),
    "668": Flag("ST", "São Tomé and Príncipe"),
    "669": Flag("SZ", "Swaziland"),
    "670": Flag("TD", "Chad"),
    "671": Flag("TG", "Togo"),
    "672": Flag("TN", "Tunisia"),
    "674": Flag("TZ", "Tanzania"),
    "675": Flag("UG", "Uganda"),
    "676": Flag("CD", "Democratic Republic of the Congo"),
    "677": Flag("TZ", "Tanzania"),
    "678": Flag("ZM", "Zambia"),
    "679": Flag("ZW", "Zimbabwe"),
    "701": Flag("AR", "Argentine Republic"),
    "710": Flag("BR", "Brazil"),
    "720": Flag("BO", "Bolivia"),
    "725": Flag("CL", "Chile"),
    "730": Flag("CO", "Colombia"),
    "735": Flag("EC", "Ecuador"),
    "740": Flag("FK", "Falkland Islands"),
    "745": Flag("GF", "French Guiana"),
    "750": Flag("GY", "Guyana"),
    "755": Flag("PY", "Paraguay"),
    "760": Flag("PE", "Peru"),
    "765": Flag("SR", "Suriname"),
    "770": Flag("UY", "Uruguay"),
    "775": Flag("VE", "Venezuela"),
}


def flag_for_mmsi(mmsi: int) -> Flag | None:
    """Resolve an MMSI to its flag state, or None if it has no meaningful one.

    Two rules, both load-bearing.

    Exactly nine digits: `mmsi` is stored as a BigInteger, so the integer
    conversion has already destroyed any leading zeros. Coast station
    `002320123` reaches us as 2320123, whose first three digits are "232" -- a
    valid MID (United Kingdom) and a confident country label on something that
    is not a ship. Requiring nine digits rejects every leading-zero form
    (`00MID` coast stations, `0MID` ship groups) before the lookup runs.

    A known MID: assigned MIDs occupy 201-775, and every non-ship-station form
    in the ITU numbering plan begins outside that range -- `98MID` craft
    associated with a parent ship, `99MID` aids to navigation, `111MID` SAR
    aircraft, `8MID` handheld, and the `970`/`972`/`974` SART/MOB/EPIRB beacons,
    which carry no MID at all. So a bare table lookup fails closed on all of
    them with no prefix dispatch: they return None and simply show no flag.
    Deliberately not decoding those prefixes -- it would put a country label on
    objects that are not vessels.
    """
    digits = str(mmsi)
    if len(digits) != 9:
        return None
    return MID_COUNTRIES.get(digits[:3])
