# Generated by Claude. Revisit when ready
"""SAR vessel detection — Sentinel-1 via Copernicus Data Space Ecosystem (CDSE).

Pipeline (per ROI, per pass):
  1. catalog search  → find the Sentinel-1 IW GRDH VV+VH scenes covering the ROI
  2. pixel fetch      → read the VV/VH backscatter for the ROI window  [DEFERRED]
  3. detection        → YOLOv8 (fine-tuned on a SAR ship dataset) → centroids  [DEFERRED]

Credit budget: 30,000 Processing Units (PU) / month.
  - Catalog search (this module's `search_scenes`) hits the CDSE OData catalogue,
    which is **free** (0 PU) and needs no auth — use it for all discovery.
  - Only the pixel-fetch step spends PU/quota. When it's built, prefer downloading
    the GRD product or windowed COG reads via GDAL `/vsicurl` (≈0 PU) over the
    Sentinel Hub Process API (PU-metered). Never drive discovery through the
    Copernicus Browser — its visual rendering also consumes PU.

Auth: pixel fetch / Sentinel Hub will use the CDSE OAuth2 client credentials
(`CDSE_CLIENT_ID` / `CDSE_CLIENT_SECRET` in config); catalog search does not.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

import httpx

CDSE_ODATA_URL = "https://catalogue.dataspace.copernicus.eu/odata/v1/Products"

# IW Interferometric Wide-swath, GRD High-res, dual-pol VV+VH — the detected,
# analysis-ready product for ship detection over coastal water.
DEFAULT_PRODUCT = "IW_GRDH_1SDV"


@dataclass(frozen=True)
class SarScene:
    """One Sentinel-1 acquisition product covering (part of) an ROI."""

    id: str
    name: str
    sensed_at: datetime          # acquisition start (UTC) — the correlation timestamp
    footprint_wkt: str | None    # actual imaged polygon; clip dark/not-dark to this
    platform: str                # "S1A" | "S1C" | "S1D"
    is_cog: bool                 # cloud-optimized GeoTIFF variant (windowed reads)


def _bbox_to_polygon_wkt(bbox: tuple[float, float, float, float]) -> str:
    """(min_lon, min_lat, max_lon, max_lat) → closed POLYGON WKT (lon lat order)."""
    min_lon, min_lat, max_lon, max_lat = bbox
    ring = [
        (min_lon, min_lat),
        (max_lon, min_lat),
        (max_lon, max_lat),
        (min_lon, max_lat),
        (min_lon, min_lat),
    ]
    coords = ",".join(f"{lon} {lat}" for lon, lat in ring)
    return f"POLYGON(({coords}))"


def _parse_scene(item: dict) -> SarScene:
    name: str = item["Name"]
    start = item["ContentDate"]["Start"].replace("Z", "+00:00")
    footprint = item.get("Footprint")
    return SarScene(
        id=item["Id"],
        name=name,
        sensed_at=datetime.fromisoformat(start).astimezone(timezone.utc),
        footprint_wkt=footprint if isinstance(footprint, str) else None,
        platform=name[:3],
        is_cog=name.endswith("_COG.SAFE"),
    )


async def search_scenes(
    bbox: tuple[float, float, float, float],
    start: datetime,
    end: datetime,
    *,
    product: str = DEFAULT_PRODUCT,
    client: httpx.AsyncClient | None = None,
) -> list[SarScene]:
    """List Sentinel-1 scenes intersecting `bbox` between `start` and `end`.

    Hits the free, unauthenticated CDSE OData catalogue (0 PU). Returns scenes
    ordered by acquisition time. Each scene's `sensed_at` is the timestamp to
    correlate AIS against; `footprint_wkt` is the polygon to clip results to.
    """
    polygon = _bbox_to_polygon_wkt(bbox)
    filt = (
        "Collection/Name eq 'SENTINEL-1' "
        f"and OData.CSC.Intersects(area=geography'SRID=4326;{polygon}') "
        f"and ContentDate/Start gt {start.astimezone(timezone.utc):%Y-%m-%dT%H:%M:%S.000Z} "
        f"and ContentDate/Start lt {end.astimezone(timezone.utc):%Y-%m-%dT%H:%M:%S.000Z} "
        f"and contains(Name,'{product}')"
    )
    params = {
        "$filter": filt,
        "$orderby": "ContentDate/Start asc",
        "$select": "Id,Name,ContentDate,Footprint",
        "$top": "200",
    }

    owns_client = client is None
    client = client or httpx.AsyncClient(timeout=30.0)
    try:
        resp = await client.get(CDSE_ODATA_URL, params=params)
        resp.raise_for_status()
        return [_parse_scene(item) for item in resp.json().get("value", [])]
    finally:
        if owns_client:
            await client.aclose()


async def fetch_scene_pixels(scene: SarScene, bbox: tuple[float, float, float, float]):
    """Read the VV/VH backscatter for `bbox` from `scene`.  [DEFERRED]

    Decision pending (see module docstring): GRD/COG download via CDSE OData /
    GDAL `/vsicurl` (≈0 PU, more processing code) vs. Sentinel Hub Process API
    (PU-metered, analysis-ready). Caches to `data/` so reprocessing is free.
    """
    raise NotImplementedError("SAR pixel fetch not implemented yet")


async def detect_vessels(scene: SarScene, bbox: tuple[float, float, float, float]):
    """Run ship detection on the SAR chip → (lon, lat, confidence) centroids.  [DEFERRED]

    YOLOv8 fine-tuned on a SAR ship dataset (HRSID / SSDD). Detection runs over
    whatever pixels exist; the footprint clip happens downstream in fusion.
    """
    raise NotImplementedError("SAR vessel detection not implemented yet")
